apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  labels:
    app: nginx
spec:
  secretName: nginx-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - example.com.com # Replace with your organization name
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - nginx.example.com.np # Replace with your domain name
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
